### ISSUE TITLE
Latest VMWare image stuck in GRUB after setup 

### ISSUE THREAD

**Issue by matthiasg** [joyent/smartos-live#516] opened 2015-11-25 12:09 UTC
We just downloaded the most recent smartos vmware live image and started it in vmware player. The setup walks us through (nice improvements there) so we can setup networking etc. and formatting the 20GB drive with default settings. In the end it prompts us to reboot.

After the reboot we dont get the normal Grub Menu, but instead are placed inside the GRUB shell and we dont really know what to do here ? What went wrong ? Does anybody have an idea ? We reproduced that on 2 different machines.

PS: By default it said it formatted the c0t1d0 disk with 20GB so it shouldnt be that we have overwritten the 'usb' stick. And in any case then it shouldnt show GRUB.

**Comment by jperkin** [comment] 2015-11-25 12:18
This is a duplicate of #506.  I'll close this one, feel free to subscribe to #506 to track progress on this issue there.  Thanks.

**Closed by jperkin** 2015-11-25 12:18 UTC

**Comment by matthiasg** [comment] 2015-11-25 12:20
thanks .. i didnt see that other issue (was searching for GRUB in github)
