### ISSUE TITLE
Build failed

### ISSUE THREAD

**Issue by MrOffline77** [joyent/smartos-live#896] opened 2020-01-27 12:36 UTC
Hi,
our build fails with master and the two 2020 release branches. I have no clue what it could be. Can you help me ?

```
./../../../gcc-gcc-7.4.0-il-1-32strap/./libstdc++-v3/libsupc++/new_opa.cc:47:9: error: '::aligned_alloc' has not been declared
 using ::aligned_alloc;
         ^~~~~~~~~~~~~
../../../../gcc-gcc-7.4.0-il-1-32strap/./libstdc++-v3/libsupc++/new_opa.cc: In function 'void* operator new(std::size_t, std::align_val_t)':
../../../../gcc-gcc-7.4.0-il-1-32strap/./libstdc++-v3/libsupc++/new_opa.cc:128:20: error: '__gnu_cxx::aligned_alloc' has not been declared
   using __gnu_cxx::aligned_alloc;
                    ^~~~~~~~~~~~~
../../../../gcc-gcc-7.4.0-il-1-32strap/./libstdc++-v3/libsupc++/new_opa.cc:129:33: error: 'aligned_alloc' was not declared in this scope
   while (__builtin_expect ((p = aligned_alloc (align, sz)) == 0, false))
                                 ^~~~~~~~~~~~~
../../../../gcc-gcc-7.4.0-il-1-32strap/./libstdc++-v3/libsupc++/new_opa.cc:129:33: note: suggested alternative:
In file included from /usr/include/stdlib.h:39:0,
                 from /root/smartosbuild/building-now/smartos-live/projects/illumos-extra/gcc7/gcc-gcc-7.4.0-il-1-32strap.build/i386-pc-solaris2.11/libstdc++-v3/include/cstdlib:75,
                 from /root/smartosbuild/building-now/smartos-live/projects/illumos-extra/gcc7/gcc-gcc-7.4.0-il-1-32strap.build/i386-pc-solaris2.11/libstdc++-v3/include/stdlib.h:36,
                 from ../../../../gcc-gcc-7.4.0-il-1-32strap/./libstdc++-v3/libsupc++/new_opa.cc:27:
/usr/include/iso/stdlib_c11.h:60:14: note:   'std::aligned_alloc'
 extern void *aligned_alloc(size_t, size_t);
              ^~~~~~~~~~~~~
Makefile:936: recipe for target 'new_opa.lo' failed
gmake[5]: *** [new_opa.lo] Error 1
gmake[5]: *** Waiting for unfinished jobs....
In file included from ../../../../gcc-gcc-7.4.0-il-1-32strap/./libstdc++-v3/libsupc++/del_opa.cc:38:0:
/root/smartosbuild/building-now/smartos-live/projects/illumos-extra/gcc7/gcc-gcc-7.4.0-il-1-32strap.build/i386-pc-solaris2.11/libstdc++-v3/include/cstdlib:132:11: error: '::aligned_alloc' has not been declared
   using ::aligned_alloc;
           ^~~~~~~~~~~~~
Makefile:944: recipe for target 'del_opa.lo' failed
gmake[5]: *** [del_opa.lo] Error 1
gmake[5]: Leaving directory '/root/smartosbuild/building-now/smartos-live/projects/illumos-extra/gcc7/gcc-gcc-7.4.0-il-1-32strap.build/i386-pc-solaris2.11/libstdc++-v3/libsupc++'
Makefile:510: recipe for target 'all-recursive' failed
gmake[4]: *** [all-recursive] Error 1
gmake[4]: Leaving directory '/root/smartosbuild/building-now/smartos-live/projects/illumos-extra/gcc7/gcc-gcc-7.4.0-il-1-32strap.build/i386-pc-solaris2.11/libstdc++-v3'
Makefile:417: recipe for target 'all' failed
gmake[3]: *** [all] Error 2
gmake[3]: Leaving directory '/root/smartosbuild/building-now/smartos-live/projects/illumos-extra/gcc7/gcc-gcc-7.4.0-il-1-32strap.build/i386-pc-solaris2.11/libstdc++-v3'
Makefile:17595: recipe for target 'all-stage1-target-libstdc++-v3' failed
gmake[2]: *** [all-stage1-target-libstdc++-v3] Error 2
gmake[2]: Leaving directory '/root/smartosbuild/building-now/smartos-live/projects/illumos-extra/gcc7/gcc-gcc-7.4.0-il-1-32strap.build'
Makefile:24519: recipe for target 'stage1-bubble' failed
gmake[1]: *** [stage1-bubble] Error 2
gmake[1]: Leaving directory '/root/smartosbuild/building-now/smartos-live/projects/illumos-extra/gcc7/gcc-gcc-7.4.0-il-1-32strap.build'
Makefile:24903: recipe for target 'bootstrap' failed
gmake: *** [bootstrap] Error 2
../Makefile.targ:27: recipe for target 'all_autoconf_32' failed
gmake[2]: *** [all_autoconf_32] Error 2
gmake[2]: Leaving directory '/root/smartosbuild/building-now/smartos-live/projects/illumos-extra/gcc7'
Makefile:160: recipe for target '/root/smartosbuild/building-now/smartos-live/proto.strap/usr/gcc/7/bin/gcc' failed
gmake[1]: *** [/root/smartosbuild/building-now/smartos-live/proto.strap/usr/gcc/7/bin/gcc] Error 2
gmake[1]: Leaving directory '/root/smartosbuild/building-now/smartos-live/projects/illumos-extra'
failed to build install_strap
Makefile:351: recipe for target '0-strap-stamp' failed
gmake: *** [0-strap-stamp] Error 1
```

Thank you very much !

**Comment by jperkin** [comment] 2020-01-27 12:45
This is likely caused by building on a PI that does not have a fix for https://www.illumos.org/issues/9545 (https://github.com/illumos/illumos-gate/commit/0df48811699b83d09c552548effcb1718d6ff1d0)

**Comment by jlevon** [comment] 2020-01-27 12:46
Please specify the exact build environment next time, thanks!
As there is no bug in smartos-live itself here, I'm closing this.

**Closed by jlevon** 2020-01-27 12:46 UTC

**Comment by MrOffline77** [comment] 2020-01-27 16:35
@jlevon Hi,
I've recreated a complete new build env as describe in the readme. When i try to build from master i stuck here 

```
ld: fatal: file /lib/amd64/libc.so: version 'ILLUMOS_0.26' does not exist:
        required by file /opt/SmartOS/build-cache/2018Q4/x86_64/7d3d5fd52c4f9652ad8735869512edc363e630ce/usr/gcc/7/bin/../lib/gcc/i386-pc-solaris2.11/7.4.0/../../../amd64/libssp.so.0
ld: fatal: file /lib/amd64/libc.so: version 'ILLUMOS_0.26' does not exist:
        required by file /opt/SmartOS/build-cache/2018Q4/x86_64/7d3d5fd52c4f9652ad8735869512edc363e630ce/usr/gcc/7/bin/../lib/gcc/i386-pc-solaris2.11/7.4.0/../../../amd64/libgcc_s.so.1
ld: fatal: file processing errors. No output written to smatch
```

Any ideas ?

**Comment by jasonbking** [comment] 2020-01-27 16:50
Try building on a SmartOS version 20180816T002409 or later

**Comment by MrOffline77** [comment] 2020-01-28 13:59
@jasonbking thank you very much !!! This did the trick. 
Nevertheless I'm getting now stuck during `gmake live`
Thank you very much <3 

PS: The Zone is setup like in the readme and the build is executed as root user. So there should be no permission problem. 

```
### Building platform image #########################################

  * Build Stamp: "20200128T094646Z"
  * Manifest File: "/root/smartosbuild/building-now/smartos-live/manifest.gen"
  * Output Directory: "/root/smartosbuild/building-now/smartos-live/output"
  * Input Directory[0]: "/root/smartosbuild/building-now/smartos-live/proto"
  * Input Directory[1]: "/root/smartosbuild/building-now/smartos-live/man/man"

Checking manual pages...                                                                                                                                                                    ... done
Checking timezone files...                                                                                                                                                                  ... done
Checking microcode files...                                                                                                                                                                 ... done
Creating temporary directory...                                                                                                                                                             ... 
  * Temporary Directory: "/tmp/build_live-0.89543"
(cont.) Creating temporary directory...                                                                                                                                                     ... done
Creating ramdisk file "/tmp/build_live-0.89543/root.image"                                                                                                                                  ... done
Creating UFS file system (/)                                                                                                                                                                ... done
Creating ramdisk file "/tmp/build_live-0.89543/usr.image"                                                                                                                                   ... done
Creating UFS file system (/usr)                                                                                                                                                             ... done (2s)
Copying files from proto areas to image                                                                                                                                                     ... done (3s)
Generating whatis database                                                                                                                                                                  ... done
Importing GZ SMF manifests                                                                                                                                                                  ... done (27s)
Building SMF seeds                                                                                                                                                                          ... done (10s)
Setting random "root" password                                                                                                                                                              ... 
  * Password: "Gohchet7eiwaegoo"
(cont.) Setting random "root" password                                                                                                                                                      ... done
Building "/etc/release" file                                                                                                                                                                ... 

BUILD FAILURE:
  [  2] bi_gen_etcrelease
        (file "./tools/build_live" line 414)
  [  3] main
        (file "./tools/build_live" line 943)

CLEANING UP ON FAILURE ...
... DONE

build_live: ERROR: failed to build "/etc/release" file
gmake: *** [Makefile:158: live] Error 1
```

**Comment by jserviceorg** [comment] 2020-01-29 12:01
edit tools/build_live and change line #1 to #!/bin/bash -x

run again, maybe this helps

cheers,

Juergen

**Comment by sjorge** [comment] 2020-01-29 12:03
Do you have "fs_allowed": "ufs,pcfs,tmpfs" set for the zone?

**Comment by MrOffline77** [comment] 2020-01-29 14:07
Hi, thanks for your suggestions. 

@jserviceorg same result with `#!/bin/bash -x`
@sjorge 
```
"zonename": "b76ace93-c1e2-eabf-c299-f4e76041a1e3",
  "autoboot": true,
  "brand": "joyent",
  "limit_priv": "default,sys_time",
  "fs_allowed": "ufs,pcfs,tmpfs",
  "v": 1,
```

**Comment by jserviceorg** [comment] 2020-01-29 14:12
result is the same for sure, but you should get debuggable output.

**Comment by timfoster** [comment] 2020-01-29 14:18
What happens when you run `./tools/build_etc_release` from the top of your workspace?

Example output from an old workspace I had lying around:
```
timf@smartos-build (master) ./tools/build_etcrelease  -v foo
                     SmartOS foo x86_64
                       Copyright 2020 Joyent, Inc.

  Built with the following components:

[
    {
        "repo": "smartos-live",
        "branch": "master",
        "commit_date": "1579275103",
        "rev": "40cbb7001154e2ba5e8e13d5e5b6c1ac718b6ace",
        "url": "git@github.com:joyent/smartos-live.git"
    },
    {
        "repo": "illumos-joyent",
        "branch": "master",
        "commit_date": "1579177173",
        "rev": "d3f83376d2ed784ca0a6ba3d8cd1fdaee338f1c4",
        "url": "https://github.com/joyent/illumos-joyent.git"
    },
    {
        "repo": "illumos-extra",
        "branch": "master",
        "commit_date": "1571766210",
        "rev": "7d3d5fd52c4f9652ad8735869512edc363e630ce",
        "url": "https://github.com/joyent/illumos-extra.git"
    },
    {
        "repo": "kvm",
        "branch": "master",
        "commit_date": "1570451135",
        "rev": "9ad0cc7792fc1f0e0fc8985ba8810362707b9b20",
        "url": "https://github.com/joyent/illumos-kvm.git"
    },
    {
        "repo": "kvm-cmd",
        "branch": "master",
        "commit_date": "1566942834",
        "rev": "41e7c3e192eb39bb5ced7667fdc12ad2b33e646d",
        "url": "https://github.com/joyent/illumos-kvm-cmd.git"
    },
    {
        "repo": "mdata-client",
        "branch": "master",
        "commit_date": "1482175115",
        "rev": "dbb3fdec26373f8e86c9ea0057ebba48581ff476",
        "url": "https://github.com/joyent/mdata-client.git"
    },
    {
        "repo": "ur-agent",
        "branch": "master",
        "commit_date": "1571591123",
        "rev": "6eee05e13ff33d2e1913d7ce9c9ff4b89bbd0122",
        "url": "https://github.com/joyent/sdc-ur-agent.git"
    }
]
timf@smartos-build (master)
```

**Comment by MrOffline77** [comment] 2020-01-29 14:22
@jserviceorg yes of course :D, but there is nothing you wouldn't expect there. No error showing up etc. 

@timfoster ( last time cloned yesterday ) 
```
                     SmartOS foo x86_64
                       Copyright 2020 Joyent, Inc.

  Built with the following components:

[
    {
        "repo": "smartos-live",
        "branch": "master",
        "commit_date": "1580131179",
        "rev": "aaa890e038179e0710b6ce3420bb5ccbe3858e96",
        "url": "https://github.com/joyent/smartos-live.git"
    },
    {
        "repo": "illumos-joyent",
        "branch": "master",
        "commit_date": "1580211558",
        "rev": "ee930d2f04dcbdb046103cf48945c9e0643f47d7",
        "url": "https://github.com/joyent/illumos-joyent.git"
    },
    {
        "repo": "illumos-extra",
        "branch": "master",
        "commit_date": "1571766210",
        "rev": "7d3d5fd52c4f9652ad8735869512edc363e630ce",
        "url": "https://github.com/joyent/illumos-extra.git"
    },
    {
        "repo": "kvm",
        "branch": "master",
        "commit_date": "1570451135",
        "rev": "9ad0cc7792fc1f0e0fc8985ba8810362707b9b20",
        "url": "https://github.com/joyent/illumos-kvm.git"
    },
    {
        "repo": "kvm-cmd",
        "branch": "master",
        "commit_date": "1566942834",
        "rev": "41e7c3e192eb39bb5ced7667fdc12ad2b33e646d",
        "url": "https://github.com/joyent/illumos-kvm-cmd.git"
    },
    {
        "repo": "mdata-client",
        "branch": "master",
        "commit_date": "1482175115",
        "rev": "dbb3fdec26373f8e86c9ea0057ebba48581ff476",
        "url": "https://github.com/joyent/mdata-client.git"
    },
    {
        "repo": "ur-agent",
        "branch": "master",
        "commit_date": "1571591123",
        "rev": "6eee05e13ff33d2e1913d7ce9c9ff4b89bbd0122",
        "url": "https://github.com/joyent/sdc-ur-agent.git"
    }
]
```
