### ISSUE TITLE
Unable to boot smartos-live at Intel NUC 7i5BNH

### ISSUE THREAD

**Issue by ricco386** [joyent/smartos-live#727] opened 2017-06-07 15:14 UTC
I have downloaded latest image from [official page](https://wiki.smartos.org/display/DOC/Download+SmartOS) and created USB image according [wiki](https://wiki.smartos.org/display/DOC/Creating+a+SmartOS+Bootable+USB+Key). When I try to boot from the usb system freeze.

Build version:
SunOS Release 5.11 Version joyent_20170601T212107Z 64-bit

Hardware:
Intel NUC 7i5BNH
Intel Core i5 7260U

Last messages in verbose boot mode:
```
ramdisk0 at root
ramdisk0 is /ramdisk
root on /ramdisk:a fstype ufs
```

Possibly related to #722 as without the verbose boot mode. I am stuck just after grub with blinking cursor.

**Comment by rmustacc** [comment] 2017-06-08 01:05
Hmm, so I guess these are the Kaby Lake based NUCs, correct? So, in this case we are getting to the OS, but something is going wrong in early boot it sounds like. We may need to use kmdb to step through a bit and see what's going on.

**Comment by ricco386** [comment] 2017-06-28 09:30
Yes it is. I have done further testing and identified the issue better. It seems that Intel Skylake/Kaby Lake processors have broken hyper-threading. I have come across issue mentioned in [Debian mailing list](https://lists.debian.org/debian-user/2017/06/msg01010.html). Unfortunatelly in my case disabling hyper-threading in BIOS didnt help.

In the time of reporting issue same behaviour was both when booting from USB and also if I run Linux and do a nested virtualization in KVM and booted SmartOS. However in the mean time I am not able to reprodcu this issue in KVM (neither with hyper-threading nor without it), but the issue is still present if I want to boot from USB directly on hardware (both with hyper-threading also without it).

BIOS info:

Intel Desktop Board NUC7i5BNB
BIOS version: BNKBL357.86A.0042.2017.0303.1854

More info about mu hardware (I got the when I booted CentOS):

```bash
[root@nanuk ~]# dmidecode -t processor | grep HTT
		HTT (Multi-threading)
[root@nanuk ~]# cat /proc/cpuinfo |grep processor
processor	: 0
processor	: 1
processor	: 2
processor	: 3
[root@nanuk ~]# cat /proc/cpuinfo |grep name
model name	: Intel(R) Core(TM) i5-7260U CPU @ 2.20GHz
model name	: Intel(R) Core(TM) i5-7260U CPU @ 2.20GHz
model name	: Intel(R) Core(TM) i5-7260U CPU @ 2.20GHz
model name	: Intel(R) Core(TM) i5-7260U CPU @ 2.20GHz
```

After disabled hyperthreading:
```bash
[root@nanuk ~]# dmidecode -t processor | grep HTT
		HTT (Multi-threading)
[root@nanuk ~]# cat /proc/cpuinfo |grep processor
processor	: 0
processor	: 1
[root@nanuk ~]# cat /proc/cpuinfo |grep name
model name	: Intel(R) Core(TM) i5-7260U CPU @ 2.20GHz
model name	: Intel(R) Core(TM) i5-7260U CPU @ 2.20GHz
```

I am able to select .... and I got the debug prompt: 
```
Loading kmdb...

Welcome to kmdb
Loaded modules: [ unix krtld genuix ]
[0]>
```

But not sure what to do next in order to help to resolve this issue?

**Comment by vrou** [comment] 2017-06-30 18:10
Hi,

I have the same issue, though I am using the NUC7I5BNH kit, but the same CPU.

I have upgraded to BIOS version 47, which should fix the HT bug, but no luck getting further than you.

**Comment by vrou** [comment] 2017-07-01 07:53
I researched a bit more yesterday, and found the following reference to a boot message I also got when I booted the SmartOS image:
`WARNING: Couldn't read ACPI SRAT table from BIOS. lgrp support will be limited to one group.`
http://blog.alainodea.com/en/article/445/smartos-on-multi-socket-and-the-acpi-srat

Could this NUMA/ACPI SRAT conflict be the reason behind this?

Today I also tried to boot on a OmniOS r151022 stable release, which ended up with the same result I got with the latest SmartOS image, minus the

**Comment by rmustacc** [comment] 2017-07-01 17:01
The NUMA/ACPI srat warning is probably a red herring here. In general, we'd like to be able to inject an NMI when this happens, but I don't think there's a good way on the NUC to do that. Maybe a first order approximation is to add the -v flag to the boot options in grub to get a slightly more verbose output. This won't tell us where it'll hang (usually where it hangs is the very next step), but it may give us something a bit more informative for where to start looking in kmdb.

The idea with kmdb is that we could single step to the point where we know it fails, but without having a starting point, that might be a little too painful. Alternatively, we may be able to enable the alternate break sequence (@jclulow do you remember how to do that exactly?) and use that to drop into kmdb when we're stuck.

Thank you for your patience with this problem.

**Comment by ricco386** [comment] 2017-07-03 15:01
@vrou If ACPI SRAT is not available in your BIOS configuration, disable NUMA/Node interleaving. Otherwise the following message may appear during boot time:
`WARNING: Couldn't read ACPI SRAT table from BIOS. lgrp support will be limited to one group.` 

@rmustacc
Problem seems to be in `startup_modules` however I have encountered two different scenarios. If i set break point to `startup_end` debuger freeze, same with `segkmem_gc` debuger is also frozen but system seems to be continue booting, until the message in verbose mode:
```
ramdisk0 at root
ramdisk0 is /ramdisk
root on /ramdisk:a fstype ufs
```

I have tried to find out the point where debuger is freezing, it seems that `setup_ddi` looops in cycle and freeze at some point, I have tried to set break point at `e_ddi_instance_init` and it gets there but debuger prompt is frozen. 

Break point set to `get_neighbors` and cycle run with continue I have end up with frozen debuger. Last message is 
```
<-[mkmdb: stop at ndi_hold_devi
kmdb: target stopped at:
ndi_hold_devi: pushq %rbp
```

**Comment by jclulow** [comment] 2017-07-03 16:23
It's possible that you can break into the debugger with the system console keyboard with one of the key combinations {{F1+A}}, or {{Shift+Pause}}.  Does that work?

**Comment by ricco386** [comment] 2017-07-04 07:47
@jclulow no once it freeze, it is frozen and I can only turn the machine off with button, no other action is possible (I have tried your key combinations, and also others).

**Comment by secult** [comment] 2017-07-17 11:39
I'm reporting a freeze on the same place with:
Lenovo Thinkpad T470p
Intel Core i5-7300HQ
Bios is up to date (v 1.13) from June 2017.
I managed to workaround this point by disabling **both Intel SpeedStep technology and CPU Power Management** in BIOS.

**Comment by YanChii** [comment] 2017-07-17 12:12
Unfortunately Intel NUC doesn't have an option to disable SpeedStep. Thus we cannot test it. But seems to me a good hint anyway.

**Comment by nerakhon** [comment] 2017-07-28 07:08
Do we know if the broadwell NUCs still work? I am deciding on which NUC to purchase for my home smartos box, so I'd like to know if it is safe to use the broadwell one, or if there is some valid workaround for the skylake/kaby lake ones?

**Comment by ricco386** [comment] 2017-07-28 09:06
In February I have tried SmartOS on Intel NUC 5I7RYH which has CPU Intel Core i7 5557U 3.4GHz Broadwell and it was working fine.

My colleague @secult has installed Danube Cloud (SmartOS based system) on this NUC and wrote a [blog](https://danubecloud.com/running-danube-cloud-on-htpc/) about it.

I have experienced issues only with this newer NUC (Skylake/Kaby Lake) version.

**Comment by pims** [comment] 2017-09-26 02:08
I’m also interested in purchasing a NUC to run SmartOS.
Did anyone figure this out?

**Comment by gbmeuk** [comment] 2017-10-03 16:02
@pims, I run on i3 and i5 fine but did have to update the BIOS on i5. Afterwards, everything works fine.

**Comment by ricco386** [comment] 2017-10-05 11:41
@pims both Skylake/Kaby Lake and Broadwell have i3, i5 processors. It was working fine on Broadwell, reported issue is for Skylake/Kaby Lake.
@gbmeuk Which one do you have?

**Comment by rmustacc** [comment] 2017-10-05 14:43
I'll have to double check things, but IIRC, the skylake based processors were fine and we've only had issues on kaby lake at the moment.

**Comment by davefinster** [comment] 2017-10-25 05:12
Seem to have stuck this issue with an associates custom-build machine. CPU is a Intel® Core i3-8100 Processor (Coffee Lake) running on top of a Gigabyte Z370M D3H. 

Went through and disabled all the shiny BIOS features including Speed Step. This particular CPU doesn't have HyperThreading  and of course being a consumer board doesn't have any out of band management. The key combinations suggested by jclulow are also ineffective.

**Comment by YanChii** [comment] 2017-10-25 15:08
Hi,
I have more info about the problem. The frozen console is ACPI related. I've traced down the instruction where the console becomes unresponsive. Steps to reproduce:
1. at kmdb prompt before kernel init, set 
```
::bp -Dn 1 acpica`AcpiOsWritePort
:c
```
2. at breakpoint, set
```
.+0x95::bp
:c
```
3. the problematic instruction is `outb (%dx)` (with %rdx=`0xb2` and %rax=`a0`)
Stepping over this instruction freezes the debugger.

Looks like acpica bug?

Anyway I've managed to get over this by rewriting the `outb` destination (needs to be done several times because of loops):
```
0>dx
:c
```
With this, I'm able to continue debugging far behind the place where @ricco386 ended up with unresponsive console.

The actual problem is in the ```xhci`xhci_controller_takeover``` function, more specifically, instruction ```movl %edx,(%rsi)``` in ```ddi_io_put32+0x15```.

Steps to get there:
```
::bp -Dn 1 -c '.+0x95::bp -c "0>dx;::cont" ; ::cont' acpica`AcpiOsWritePort
::bp -Dn 1 -c 'ddi_io_put32+0x15::bp ; ::cont' xhci`xhci_controller_takeover
:c
```
If you need any more info, please ask. Currently, I don't know how to help more.
Thanks you guys in advance for looking at it.

Jan

**Comment by rmustacc** [comment] 2017-10-25 15:22
@YanChii Thanks for the additional data here. Can you share the stack at that point that you're skipping over the AcpiOsWritePort?

Regarding the xhci takeover, there are a couple of different things that this could mean. One is that depending on how the keyboard is wired up in this case (presumably over USB) that we lose the ability to actually use the keyboard until the stack brings up enough of the other plumbing.

The second possibility (maybe more likely) is that we're writing a value in such a way that firmware doesn't like it. This may or may not have something to do with the ACPI tables that are present and the ports that we're not writing to. The thing that might help is to know what the arguments to xhci_put32() were at the time of that last ddi_io_put32. I'm assuming that we're in the path that's trying to take over BIOS ownership, but it's possible we're not.

**Comment by YanChii** [comment] 2017-10-26 08:56
@rmustacc 
Here is the stack:
```
acpica`AcpiOsWritePort+0x95(b2, a0, 8)
acpica`AcpiHwWritePort+0xd6(b2, a0, 8)
acpica`AcpiHwSetMode+0x200(1)
acpica`AcpiEnable+0x56()
acpica`AcpiEnableSubsystem+0x124(0)
acpica`acpica_init+0x114()
acpidev`acpidev_initialize+0x105()
acpidev`acpidev_boot_probe+0x6d(0)
impl_bus_initialprobe+0x65()
impl_setup_ddi+0xcb()
create_devinfo_tree+0xbd()
setup_ddi+0x13()
startup_modules+0xf6()
startup+0x55()
main+0x3b()
_locore_start+0x90()
```

The keyboard is connected using USB. 
I've tried to set both registers to zero before the steping over `movl %edx,(%rsi)`. It caused the keyboard to keep working.. but I had to do it multiple times (probably some loop) and ended up in double fault state later.

Regarding the parameters of `xhci_put32()`, the arguments in C code are
`xhci_put32(xhcip, XHCI_R_CAP, off, val)`
But I don't see any arguments passed in `::stack`, nor the values pushed into stack before calling the `xhci_put32()`.

Any hint here?
Thx.
J.

**Comment by YanChii** [comment] 2017-10-26 09:34
I'm including also some screenshots 
![img_20171026_093904](https://user-images.githubusercontent.com/5031852/32045710-3c530dec-ba41-11e7-8bc9-e1648e690def.jpg)
![img_20171026_093926](https://user-images.githubusercontent.com/5031852/32045737-50377dfc-ba41-11e7-90da-e45208ed7917.jpg)
![img_20171025_165852](https://user-images.githubusercontent.com/5031852/32045747-597f9e12-ba41-11e7-9a35-50c6c911f4aa.jpg)

**Comment by rmustacc** [comment] 2017-10-26 13:47
The reason you won't see the values pushed on the stack there is probably because ddi_io_put32 doesn't push a frame pointer. However, knowing where we're blowing up in the xhci driver gives me an idea here. I'm going to put together a change and build an image (and provide a patch) that may address the takeover freeze. I'll try to have something before too long.

Once that's done, I'll try and get back to the acpi issue. Thanks for your help digging into this.

**Comment by rmustacc** [comment] 2017-11-02 17:04
So, there are a lot of different ways that the takeover can occur. Importantly, it's possible for ACPI to have done this such that the driver doesn't have to. The register for this capability supports 8-bit reads and writes; however, we're always doing a 32-bit write. Which means that we're rewriting the BIOS owned value. As a result, I've experimented by doing a single 8-bit write on the upper byte.

The patch also has some additional logging just to help us understand what's happening. The patch is here:

```
diff --git a/usr/src/uts/common/io/usb/hcd/xhci/xhci.c b/usr/src/uts/common/io/usb/hcd/xhci/xhci.c
index 84bd1a1..c23f66d 100644
--- a/usr/src/uts/common/io/usb/hcd/xhci/xhci.c
+++ b/usr/src/uts/common/io/usb/hcd/xhci/xhci.c
@@ -1510,9 +1510,22 @@ xhci_controller_takeover(xhci_t *xhcip)
 		return (B_FALSE);
 	}
 
+	xhci_error(xhcip, "^Capability register: 0x%x", val);
 	if (val & XHCI_BIOS_OWNED) {
+		uint8_t own;
+
+		xhci_error(xhcip, "^XHCI is BIOS owned, attempting take over");
+
+		/*
+		 * The USB Legacy support capability (USBLEGSUP) register allows
+		 * for byte-wide accesses. We take advantage of this for trying
+		 * to write the OS owned register. We do this so we don't end up
+		 * having to risk writing the HC BIOS owned bit, which could
+		 * potentially cause problems.
+		 */
 		val |= XHCI_OS_OWNED;
-		xhci_put32(xhcip, XHCI_R_CAP, off, val);
+		own = (val >> 24) & 0xff;
+		xhci_put8(xhcip, XHCI_R_CAP, off + 3, own);
 		if (xhci_check_regs_acc(xhcip) != DDI_FM_OK) {
 			xhci_error(xhcip, "failed to write BIOS take over "
 			    "registers: encountered fatal FM register error");
@@ -1520,6 +1533,7 @@ xhci_controller_takeover(xhci_t *xhcip)
 			    DDI_SERVICE_LOST);
 			return (B_FALSE);
 		}
+		xhci_error(xhcip, "^Made it past the takeover write");
 
 		/*
 		 * Wait up to 5 seconds for things to change. While this number
@@ -1529,6 +1543,7 @@ xhci_controller_takeover(xhci_t *xhcip)
 		 */
 		ret = xhci_reg_poll(xhcip, XHCI_R_CAP, off,
 		    XHCI_BIOS_OWNED | XHCI_OS_OWNED, XHCI_OS_OWNED, 500, 10);
+		xhci_error(xhcip, "^take over register poll completed with %d", ret);
 		if (ret == EIO)
 			return (B_FALSE);
 		if (ret == ETIMEDOUT) {
```

I've also gone ahead and made a new set of platform images with the vga as the default console which are available here:

[Raw Platform](https://us-east.manta.joyent.com/rmustacc/public/tmp/smartos-live-727/platform-20171101T225847Z.tgz)
[ISO Image](https://us-east.manta.joyent.com/rmustacc/public/tmp/smartos-live-727/platform-20171101T225847Z.iso)
[USB Image](https://us-east.manta.joyent.com/rmustacc/public/tmp/smartos-live-727/platform-20171101T225847Z.usb.bz2)

Thanks for your patience on this one.

**Comment by YanChii** [comment] 2017-11-02 17:13
Thanks, I'll try the new image and get back asap.
Jan

**Comment by YanChii** [comment] 2017-11-03 09:31
Now the keyboard freezes at 
```
ddi_io_put8+0x15  (movb %dl,(%rsi)
xhci_put8
xhci_controller_takeover
```
The actual code makes it further, printing all your debug (and freezes somwhere else). But there's not much I can do without a keyboard.
![img_20171103_092143](https://user-images.githubusercontent.com/5031852/32367109-43cbee0e-c081-11e7-86f1-cb73035056e5.jpg)
![img_20171103_101826](https://user-images.githubusercontent.com/5031852/32367116-4d58a732-c081-11e7-9401-404969b19fe9.jpg)
Mdb to get there:
```
::bp -Dn 1 -c '.+0x95::bp -c "0>dx;::cont" ; ::cont' acpica`AcpiOsWritePort
::bp -Dn 1 -c 'ddi_io_put8+0x15::bp; ::cont" xhci`xhci_controller_takeover
::cont
```
Thank you for your help.
Jan

**Comment by rmustacc** [comment] 2017-11-03 17:18
Hmm. So likely the change I had isn't actually changing anything and we're getting stuck elsewhere. I'm not entirely sure what the right next step is. I have two different questions to try and figure out some things.

The first is to do the ACPI workaround, but skip the xhci bits. This will be done by adding a `-B disable-xhci=true` to the boot arguments. I know this'll mean that we don't have a keyboard, but it might help us narrow down what's going on.

A second course of action is to try and turn on moddebug and just see if that gives us more information by chance. What we'll want to do is set moddebug the following way in mdb:

```
> moddebug/W 0xF0040000
```

That'll give us a bunch of additional things that are happening. I'm hoping that between the two we might be able to narrow it down. I realize that the fact that we can't use the USB keyboard in this environment in kmdb really hurts -- I'm sorry I don't have a better option quite at this time.

**Comment by YanChii** [comment] 2017-11-07 08:26
Well. Something strange happened. The OS came online into the prompt-config. But it might be an accident because it already happened to me one time before (out of hundred).
I've set `-B disable-xhci=true`, moddebug and worked around the first acpica problem.
Now I have the OS running and I'm a bit afraid to shut it down :).
And the best thing is that even with `disable-xhci=true`, the USB keyboard is working.
I'm writing you this in case you'd like to run some commands from the OS itself. If you don't need anything from the OS, I'll try to replicate the successful boot.
Thx.
Jan

**Comment by rmustacc** [comment] 2017-11-08 15:22
That's good to know and really helps us focus our inquiry. So we know that there's something buggy going on in the xhci driver that's probably causing some kind of deadlock (though what, I can't say) or livelock. I'll need a little bit to think how we can better root cause what's happening there. I'll see if I can investigate if there are any other xhci related circumstances that things go awry that we can leverage for this.

I guess in parallel we should really figure out the ACPI workaround and why that's required. Thanks for all your help through this.

**Comment by YanChii** [comment] 2017-11-08 16:15
NP, glad to help.
More info: the machine boots only when all 3 factors are in place:
1. `-B disable-xhci=true`
2. ```::bp -Dn 1 -c '.+0x95::bp -c "0>dx;::cont" ; ::cont' acpica`AcpiOsWritePort```
3. `moddebug/W 0xF0040000`

If I omit any of them, it hangs. Yes, it hangs even without moddebug.

And without disable-xhci, the last thing the moddebug prints is this:
![img_20171108_170741](https://user-images.githubusercontent.com/5031852/32559718-20f2d688-c4a8-11e7-8902-299bec4ac689.jpg)

Jan

**Comment by jmarcedwards** [comment] 2018-04-06 19:34
Was this problem every solved on this NUC series?

**Comment by YanChii** [comment] 2018-04-06 20:42
I'm not aware of that. The only thing that moved until the last conversation is this:
https://www.mail-archive.com/smartos-discuss@lists.smartos.org/msg05726.html
Jan

**Comment by rmustacc** [comment] 2018-04-06 20:56
No, it hasn't sorry. It's in our queue to finish digging into.

**Comment by jasonbking** [comment] 2018-07-19 02:45
This is probably a bit of a long shot, but I've been working on an early boot hang (my system seems to trigger it pretty easily).  There are _some_ similarities to the hangs I've experienced (though not exact -- so it's _possible_ it might be the same issue, but is far from definitive).  I have _test_ images with the proposed fix for my hang available at:

https://us-east.manta.joyent.com/jbk/public/OS-7079/platform-20180719T001516Z.iso
https://us-east.manta.joyent.com/jbk/public/OS-7079/platform-20180719T001516Z.usb.bz2

NOTE: These images are set to enter kmdb upon an NMI (the SmartOS default is to panic, however having the system panic where my hang was occurring wasn't very useful -- though this may not matter for your system).

If you'd like, feel free to give them a try and see if they work (if you do try them out, please let me know one way or the other what the results are -- as I said, it's probably a long shot that it's the same issue, but might be worth at least giving it a try).  It's sufficient if the system comes up to the installer (it's not necessary to install SmartOS if you don't wish to).

**Comment by rmustacc** [comment] 2018-07-26 01:10
Thanks everyone for your patience and assistance to date. I've been digging into this and have arrived at a root cause and with a WIP fix in place am able to boot successfully on a Kaby Lake NUC. The problem basically is a logic bug in the core ACPI processing code that leads to an attempt to recursively grab a mutex which is already acquired and ultimately leads to a hang.

A full analysis is available here: https://smartos.org/bugview/OS-7093. I'm hoping I'll be in a better place for getting test bits out shortly.

**Comment by jmarcedwards** [comment] 2018-07-27 13:31
Robert:

Thanks for getting this resolved. I'll also be very happy to proceed in
further testing of the fix on some Cisco UCS Kaby Lake servers. Please let
me know which patch/PR to work with, and I will proceed.

-Marc

**Comment by nerakhon** [comment] 2018-07-27 14:15
Those are amazing news, I just barely managed to scrape a v6 NUC for my home lab start and if v7 ones start working after this then hoorray :).

If you wanted any test on the new CPUs in small scale I have a v7 NUC @work which I could borrow and test on.

Cheers,

-Jan

**Comment by rmustacc** [comment] 2018-07-27 15:35
I'm hoping to get testing images up today or by Monday at the latest.
I'm just adding some extra debug information into them so if we hit
issues, we can better diagnose them.

**Comment by huang96962** [comment] 2018-07-28 02:00
I update acpica to version 20171110, it work fine.

**Comment by rmustacc** [comment] 2018-08-01 16:28
Just wanted to provide an update on this. We noticed that there were problems on a couple of different platforms that were seeing ACPI errors after this update. While it doesn't occur on the NUCs, we're working to root cause those and understand them before we get wider testing done.

**Comment by jmarcedwards** [comment] 2018-08-01 21:58
Robert:

OK...thanks for the update.  I'll continue to monitor this thread, 
anxious to test the fix.

-M

**Comment by rmustacc** [comment] 2018-08-02 15:28
On 8/1/18 19:23 , John Huang wrote:
> I uesd acpica version 20171110, it work well last year. This year, I update BIOS, I see APCI errors, but it work well. So I think we should update acpica to newest, we can get it from https://github.com/acpica/acpica/releases.
> 

Yes, we already did update to the latest release as part of this.
However, as I mentioned, we saw errors on other server platforms that
we're investigating and we're not going to move forward until we root
cause. Unfortunately, making sure that the server platforms work well
takes priority for us. We're not going to be moving forward with pushing
this into SmartOS until we root cause them, which we're working on
between us and the manufacturer.

**Comment by xmerlin** [comment] 2018-08-10 16:45
I've the same problem trying smartos 20180621T003454Z with:
- supermicro X11SRA-RF + Xeon W-2145 Skylake W
- Asrock z370 extreme4 + intel core i5 8600K

the second one boots disabling acpi (I've not tryed with the first one)

**Comment by rmustacc** [comment] 2018-08-14 01:30
I've put together the following images to help test this. Note that I've changed things such that it ends up putting a larger amount of ACPI data out to the console. There are both debug and non-debug versions present:

[non-debug raw platform](https://us-east.manta.joyent.com/rmustacc/public/preview/acpi-201808/non-debug/platform-20180807T230146Z.tgz)
[non-debug ISO vga](https://us-east.manta.joyent.com/rmustacc/public/preview/acpi-201808/non-debug/acpi-nd-vga.iso)
[non-debug ISO ttya](https://us-east.manta.joyent.com/rmustacc/public/preview/acpi-201808/non-debug/acpi-nd-ttya.iso)
[non-debug ISO ttyb](https://us-east.manta.joyent.com/rmustacc/public/preview/acpi-201808/non-debug/acpi-nd-ttyb.iso)
[non-debug USB vga](https://us-east.manta.joyent.com/rmustacc/public/preview/acpi-201808/non-debug/acpi-nd-vga.usb.bz2)
[non-debug USB ttya](https://us-east.manta.joyent.com/rmustacc/public/preview/acpi-201808/non-debug/acpi-nd-ttya.usb.bz2)
[non-debug USB ttyb](https://us-east.manta.joyent.com/rmustacc/public/preview/acpi-201808/non-debug/acpi-nd-ttyb.usb.bz2)

[debug raw platform](https://us-east.manta.joyent.com/rmustacc/public/preview/acpi-201808/debug/platform-20180807T223604Z.tgz)
[debug ISO vga](https://us-east.manta.joyent.com/rmustacc/public/preview/acpi-201808/debug/acpi-debug-vga.iso)
[debug ISO ttya](https://us-east.manta.joyent.com/rmustacc/public/preview/acpi-201808/debug/acpi-debug-ttya.iso)
[debug ISO ttyb](https://us-east.manta.joyent.com/rmustacc/public/preview/acpi-201808/debug/acpi-debug-ttyb.iso)
[debug USB vga](https://us-east.manta.joyent.com/rmustacc/public/preview/acpi-201808/debug/acpi-debug-vga.usb.bz2)
[debug USB ttya](https://us-east.manta.joyent.com/rmustacc/public/preview/acpi-201808/debug/acpi-debug-ttya.usb.bz2)
[debug USB ttyb](https://us-east.manta.joyent.com/rmustacc/public/preview/acpi-201808/debug/acpi-debug-ttyb.usb.bz2)

Please let me know if it works or fails and if it does. It'd help to know what kind of system it is / bios rev if possible. Some of this is available through smbios.

**Comment by fejfighter** [comment] 2018-08-16 12:12
Tried the non-debug USB vga on an X1 carbon 6th gen, and after a screenfull of text related acpi table output, it went to install as expected.

by comparison, lastest PI image (02/08?) got stuck with no output, as did the bloody OmniOSce and OI 2018.04 which is what got me looking at this issue. 

as mentioned, latest Lenovo X1 Carbon 6th Gen, latest BIOS, lshw output from Fedora 28
```

     *-firmware
          description: BIOS
          vendor: LENOVO
          physical id: b
          version: N23ET52W (1.27 )
          date: 07/18/2018
          size: 128KiB
          capacity: 16MiB
          capabilities: pci pnp upgrade shadowing cdboot bootselect edd int13floppy720 int5printscreen int9keyboard int14serial int17printer int10video acpi usb biosbootspecification uefi

```
if anyone has an idea on getting serial output from this laptop, I'd be happy to provide more info

**Comment by xmerlin** [comment] 2018-08-16 15:28
Tried both images on Asrock z370 extreme4 + intel core i5 8600K and boot as expected

`bios version 3.10 (10/lug/2018 - the last one)`

**Comment by rmustacc** [comment] 2018-08-16 15:33
OK, great. I'm glad to hear that. I'm going to kick off a bit more illumos-wide testing to make sure there aren't any additional regressions. I'm hoping that we'll get this back before too long then. Thanks again everyone for your patience and the reports that items are now working that previously didn't is quite encouraging.

@fejfighter the screenful of ACPI related text was purposeful in case there were issues to help folks get a sense of what was happening.

**Comment by ski2310** [comment] 2018-08-16 16:35
Worked on the following systems (that failed previously) -

Asus H110S2 - i3-6100T - bios ver. 3805
MSI C236M - i3-6100T - bios ver. 7972vDA

Also worked on these two existing systems that did not have any previous issues (regression testing).

HP DL320 G6 - X5650 - bios ver. W07
HP ML110 G7 - E3-1220 - bios ver. J01

**Comment by rmustacc** [comment] 2018-08-16 17:00
On 8/16/18 9:35 , ski2310 wrote:
> Worked on the following systems (that failed previously) -
> 
> Asus H110S2 - i3-6100T - bios ver. 3805
> MSI C236M - i3-6100T - bios ver. 7972vDA
> 
> Also worked on these two existing systems that did not have any previous issues (regression testing).
> 
> HP DL320 G6 - X5650 - bios ver. W07
> HP ML110 G7 - E3-1220 - bios ver. J01
> 
> 

Great, thank you very much for the additional tests.

Robert

**Comment by xmerlin** [comment] 2018-08-16 19:58
It works also on this system that did not have any previous issues:
supermicro x9scm-f + e3-1220v2

**Comment by fejfighter** [comment] 2018-08-16 21:02
@rmustacc makes sense, would give an insight into where it got locked up, I wasn't sure if it was just printing errors/warnings rather than general debug/info messages.

Do you have a public branch or patches sitting around? I wouldn't mind building an (installable) image from it, noting that it's definitely not production/ops criticla

**Comment by rmustacc** [comment] 2018-08-16 21:06
On 8/16/18 14:02 , Jeff Walsh wrote:
> Do you have a public branch or patches sitting around? I wouldn't mind building an (installable) image from it, noting that it's definitely not production/ops criticla

If you are on smartos-discuss, I sent mail that contains pointers to all
the git branches and where to find ACPI, etc. I can duplicate that here
if you can't find that.

**Comment by snltd** [comment] 2018-08-22 22:04
Gigabyte H110N board, with i5-6400 CPU. American Megatrends BIOS version F21 06/09/2017.

Boot locks up using a normal SmartOS image, but the system boots and runs just fine with the non-debug VGA build. Great job.

**Comment by xmerlin** [comment] 2018-08-28 01:51
supermicro X11SRA-RF + Xeon W-2145 Skylake W -> runs fine with the non debug VGA build

**Comment by YanChii** [comment] 2018-08-28 09:35
Hi @rmustacc,

We have successfully booted the Intel NUC from the beginning of this issue. This image makes it seamlessly to the prompt-config:
https://us-east.manta.joyent.com/rmustacc/public/preview/acpi-201808/non-debug/acpi-nd-vga.usb.bz2

Thank you!

Jan

**Comment by rmustacc** [comment] 2018-09-01 00:47
Thanks for the testing everyone. We've put the changes back to illumos-joyent today. This will be in the next release (in about two weeks). You can find it at https://github.com/joyent/illumos-joyent/commit/1d4a584aa3508af31fbae62e2fdac839add8ecdf.

I appreciate the patience with this one. I know it's been a major pain.

**Closed by rmustacc** 2018-09-01 00:47 UTC
