### ISSUE TITLE
IP_MULTICAST_LOOP wrong type in smartos/lx_ubuntu

### ISSUE THREAD

**Issue by riggy2013** [joyent/smartos-live#643] opened 2016-06-13 04:52 UTC
Hi,

I tried to install MINIDLNA on an lx_ubuntu 14.04 over smartos. However it reports error on this line:

```
	unsigned char loopchar = 0;

        ......

	if (setsockopt(s, IPPROTO_IP, IP_MULTICAST_LOOP, (char *)&loopchar, sizeof(loopchar)) < 0)
	{
		printf("setsockopt(udp_notify, IP_MULTICAST_LOOP): %s\n", strerror(errno));
		close(s);
		return -1;
	}
```
the error is: invalid argument.

I changed loopchar to an int type and it passed.

I tried the same code in an ubuntu bare box 14.04 and it passes.

Is it a bug in smartos?

Thanks,

David

**Comment by pfmooney** [comment] 2016-06-13 17:43
What version of the platform image are you running (uname -v)?
I believe this was fixed in [OS-5428](https://smartos.org/bugview/OS-5428).

**Comment by riggy2013** [comment] 2016-06-13 23:21
OK. Yes, I am using the old one:

SunOS homelab_dp 5.11 joyent_20160414T011743Z i86pc i386 i86pc

then i'll try the new version.

Thanks,

David

**Comment by pfmooney** [comment] 2016-06-15 19:36
Please let me know if the issue is still present on the updated PI.

**Closed by pfmooney** 2016-06-15 19:36 UTC
