### ISSUE TITLE
Latest Smartos version cannot boot Win7 x64 with KVM

### ISSUE THREAD

**Issue by GernotS** [joyent/smartos-live#792] opened 2018-07-09 07:43 UTC
All my Win7 x64 instances loop when trying to boot.
32-bit version work fine. I suspect FPU framework changes to be responsible for that.

**Comment by GernotS** [comment] 2018-07-11 18:33
There is no core, nothing useful in the logs (at least for me).
I can see the SEABIOS screen in VNC for a short while, then blank, then looping.
If I am lucky I can boot in safe mode, but on the next reboot loops again.
I could do a video of it but I guess thats not really helpful
Server 2008 and 2012 as well as Win10 run fine on the same machine
Trying to boot a win7 iso also loops.
Going back to a smartos release 4 weeks ago cures all that

**Comment by plitc** [comment] 2018-07-17 22:45
a Windows 7 x64 installation iso can not be loaded either (20180717T123432Z)

**Comment by matthiasg** [comment] 2018-08-19 06:57
Interestingly they can boot into Safe Mode with Networking, but not into VGA mode.

**Comment by rmustacc** [comment] 2018-08-24 06:44
All, I've managed to root cause this and have been able to successfully boot a win 7 installer image and am currently going through an install. I've written up the root cause in this bug: http://smartos.org/bugview/OS-7174. This was a regression introduced by the HMA work (though not eager FPU). My apologies it took us so long to get to this. If anyone would like an interim image with a fix, I'm happy to share the image that I've been using to test this. I'll keep this open until a fix has integrated.

**Comment by dbirkbeck** [comment] 2018-08-24 18:46
Thanks https://github.com/rmustacc!  I look forward to the fix being integrated.

**Comment by rmustacc** [comment] 2018-08-27 22:53
This should be dealt with in https://github.com/joyent/illumos-kvm/commit/4149738a32ab6ac380a31c309d116e3dfef47a98. The upcoming release will contain the fix for this.

**Closed** 2018-08-27 22:53 UTC
