### ISSUE TITLE
puppet crashes ruby interpreter in an Ubuntu lx zone

### ISSUE THREAD

**Issue by snltd** [joyent/smartos-live#433] opened 2015-03-31 14:24 UTC
On SmartOS build joyent_20150320T034246Z with the 818cc79e-ceb3-11e4-99ee-7bc8c674e754  lx-ubuntu-14.04 image.

Create a VM and install puppet:

```
 "brand": "lx",
 "image_uuid": "818cc79e-ceb3-11e4-99ee-7bc8c674e754",
 "alias": "lx1",
 "kernel_version": "3.13.0",
 "hostname": "lx1",
 "max_physical_memory": 2048,
 "resolvers": ["192.168.1.26", "8.8.8.8"],
 "nics": [
  {
    "nic_tag": "admin",
    "ip": "192.168.1.83",
    "netmask": "255.255.255.0",
    "gateway": "192.168.1.1",
    "primary": "1"
  }
 ],
 "customer_metadata": {
    "user-script" : "apt-get update >/var/log/1 2>&1; apt-get install -y puppet >/var/log/2 2>&1"
 }
}
```

zlogin to the VM, and create a very simple puppet manifest as `test.pp`

```
file { '/tmp/test':
        ensure => present,
}
```

then apply it

```
$ puppet apply test.pp
...
Error: Could not run command from prerun_command: Execution of '/etc/puppet/etckeeper-commit-pre' returned : /usr/lib/ruby/vendor_ruby/puppet/util.rb:295: [BUG] rb_update_max_fd: invalid fd (8) given.
```

I won't post the entire trace here, because it's long and (hopefully) trivial to reproduce. A core file is  written.

**Comment by lloydde** [comment] 2015-03-31 16:44
Thanks @snltd, will confirm now. :8ball:

**Comment by lloydde** [comment] 2015-03-31 17:50
@snltd I haven't been able to reproduce this using a newer platform image. Could you update and try again?


~~~bash
# /native/usr/bin/uname -a
SunOS ebe581d5-0569-60ae-b12e-95a1fb48b23a 5.11 joyent_20150327T214450Z i86pc i386 i86pc
# puppet apply test.pp 
Device "eth0" does not exist.
Device "eth0" does not exist.
Device "eth0" does not exist.
Device "eth0" does not exist.
Device "eth0" does not exist.
Device "lo" does not exist.
Device "lo" does not exist.
Device "lo" does not exist.
Device "lo" does not exist.
Device "lo" does not exist.
Device "eth0" does not exist.
Device "eth0" does not exist.
Device "lo" does not exist.
Device "lo" does not exist.
Warning: Could not retrieve fact fqdn
Notice: Compiled catalog for ebe581d5-0569-60ae-b12e-95a1fb48b23a in environment production in 0.11 seconds
Device "eth0" does not exist.
Device "eth0" does not exist.
Device "eth0" does not exist.
Device "eth0" does not exist.
Device "eth0" does not exist.
Device "lo" does not exist.
Device "lo" does not exist.
Device "lo" does not exist.
Device "lo" does not exist.
Device "lo" does not exist.
Device "eth0" does not exist.
Device "eth0" does not exist.
Device "lo" does not exist.
Device "lo" does not exist.
Notice: /Stage[main]/Main/File[/tmp/test]/ensure: created
Notice: Finished catalog run in 0.03 seconds
~~~

**Comment by lloydde** [comment] 2015-03-31 18:42
@snltd I also confirmed the behavior on centos-6, where we are not hitting https://smartos.org/bugview/OS-4138 , it runs cleanly there:

~~~bash
# /native/usr/bin/uname -a
SunOS 0b7f69f4-da06-ea77-f82e-a0fa92f8df06 5.11 joyent_20150327T214450Z i86pc i386 i86pc
# cat /etc/redhat-release 
CentOS release 6.6 (Final)
# uname -a
Linux 0b7f69f4-da06-ea77-f82e-a0fa92f8df06 2.6.32 BrandZ virtual linux x86_64 x86_64 x86_64 GNU/Linux
# puppet apply test.pp
Notice: Compiled catalog for 0b7f69f4-da06-ea77-f82e-a0fa92f8df06 in environment production in 0.20 seconds
Notice: /Stage[main]/Main/File[/tmp/test]/ensure: created
Notice: Finished catalog run in 0.04 seconds
~~~

**Comment by lloydde** [comment] 2015-04-01 17:21
@snltd I'll close this as already-fixed for now. Please comment/re-open if you see it again.

**Comment by snltd** [comment] 2015-04-04 16:06
I still see this with the joyent_20150403T203920Z platform image. It works fine on the lx-centos-6 and lx-debian-7 images, but 818cc79e-ceb3-11e4-99ee-7bc8c674e754  lx-ubuntu-14.04 fails as it did before.

Anything else I should try? I can send full output (1752 lines!) and/or core file if required.

**Comment by lloydde** [comment] 2015-04-04 20:04
@snltd hmm, that is perplexing. Could you put your full run in a gist? I've attached my own run, https://gist.github.com/lloydde/288cdc038775f9b5c9d1 . Anything catch your eye?

After I receive that, I'll try and reproduce on standalone virtualized SmartOS -- Monday at the earliest..

**Comment by snltd** [comment] 2015-04-05 21:45
I've done a little digging into the Ruby that's being run, and you can duplicate the crash with the following command (lifted from `def_safe_posix()` in `/usr/lib/ruby/vendor_ruby/puppet/util.rb`)

```
$ ruby -e "3.upto(256){|fd| IO::new(fd).close rescue nil}"
```

This crashes Ruby for me on Centos, Debian and Ubuntu lx zones. It works fine in a native zone and in an Ubuntu KVM on the same machine.

I've posted the output, and an strace of what goes on at https://gist.github.com/snltd/693ba930b8cf5d939fb6.

I'm happy to do whatever I can to help resolve this.

**Comment by lloydde** [comment] 2015-04-06 04:05
@snltd bizarre, I still can't reproduce in us-east-3b.api.joyent.com Are you able to try with PI joyent_20150403T144852Z ? :sake:

~~~bash
root@1a63c6ed31e3:/# /native/usr/bin/uname -a
SunOS 1a63c6ed31e3 5.11 joyent_20150403T144852Z i86pc i386 i86pc
root@1a63c6ed31e3:/# uname -a
Linux 1a63c6ed31e3 3.13.0 BrandZ virtual linux x86_64 x86_64 x86_64 GNU/Linux
root@1a63c6ed31e3:/# lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 14.04.2 LTS
Release:        14.04
Codename:       trusty
root@1a63c6ed31e3:/#  ruby --version
ruby 1.9.3p484 (2013-11-22 revision 43786) [x86_64-linux]
root@1a63c6ed31e3:/# ruby -e "3.upto(256){|fd| IO::new(fd).close rescue nil}"
root@1a63c6ed31e3:/# exit
~~~

**Comment by rmustacc** [comment] 2015-04-06 04:19
@lloydde There is no smartos release with that platform version. @snltd can you make the core available please?

**Comment by snltd** [comment] 2015-04-06 18:58
Just to be sure, I nuked the box completely, and rebuilt with joyent_20150403T203920Z. Same result. Core file at https://www.dropbox.com/s/drrj5f9vhpm4bch/core.

**Comment by snltd** [comment] 2015-05-28 21:30
This now works fine for me on SmartOS 20150514T133314Z and lx-ubuntu 43e64f3c-fdd3-4c3e-a397-c1c3c67744fa.

**Closed** 2015-05-28 21:30 UTC

**Comment by lloydde** [comment] 2015-05-28 21:44
Thanks for following up @snltd !
